# Generated by Django 3.0 on 2020-11-02 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proofmodel',
            old_name='statement',
            new_name='sentence',
        ),
        migrations.RenameField(
            model_name='proofmodel',
            old_name='statement_proof',
            new_name='sentence_proof',
        ),
    ]
