# Generated by Django 3.0 on 2020-11-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formal', '0002_auto_20201102_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='proofmodel',
            name='parent_position',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='proofmodel',
            unique_together={('parent', 'parent_position')},
        ),
    ]
