# Generated by Django 3.1.7 on 2021-03-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_auto_20210330_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfirmation',
            name='frontend_url',
            field=models.URLField(blank=True),
        ),
    ]
